///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TestPlayer
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("d792bd5b-12b2-4c77-b577-e723bb9ce635", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TestPlayerRepository repository.
        /// </summary>
        public static TestPlayerRepository repo = TestPlayerRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
            searchLastName = "";
            searchFirstName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

        string _searchLastName;

        /// <summary>
        /// Gets or sets the value of variable searchLastName.
        /// </summary>
        [TestVariable("5e8969e9-da00-4532-a2c3-07a63bcecca7")]
        public string searchLastName
        {
            get { return _searchLastName; }
            set { _searchLastName = value; }
        }

        string _searchFirstName;

        /// <summary>
        /// Gets or sets the value of variable searchFirstName.
        /// </summary>
        [TestVariable("3ff6794e-9b5f-45a0-b373-7477c9721744")]
        public string searchFirstName
        {
            get { return _searchFirstName; }
            set { _searchFirstName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Password.Password' at 25;10.", repo.Password.PasswordInfo, new RecordItemIndex(0));
            repo.Password.Password.Click("25;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}123456{LShiftKey up}' with focus on 'Password.Password'.", repo.Password.PasswordInfo, new RecordItemIndex(1));
            repo.Password.Password.PressKeys("{LShiftKey down}123456{LShiftKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Password.ButtonOK' at Center.", repo.Password.ButtonOKInfo, new RecordItemIndex(2));
            repo.Password.ButtonOK.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form1' at Center.", repo.Form1.SelfInfo, new RecordItemIndex(3));
            repo.Form1.Self.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Player.Management' at 72;13.", repo.Player.ManagementInfo, new RecordItemIndex(4));
            repo.Player.Management.Click("72;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Player.Player' at 40;10.", repo.Player.PlayerInfo, new RecordItemIndex(5));
            repo.Player.Player.Click("40;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CustomerSearch23502416.Name' at 46;10.", repo.CustomerSearch23502416.NameInfo, new RecordItemIndex(6));
            repo.CustomerSearch23502416.Name.Click("46;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$searchLastName' with focus on 'CustomerSearch23502416.Name'.", repo.CustomerSearch23502416.NameInfo, new RecordItemIndex(7));
            repo.CustomerSearch23502416.Name.PressKeys(searchLastName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CustomerSearch23502416.FirstName' at 79;5.", repo.CustomerSearch23502416.FirstNameInfo, new RecordItemIndex(8));
            repo.CustomerSearch23502416.FirstName.Click("79;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$searchFirstName' with focus on 'CustomerSearch23502416.FirstName'.", repo.CustomerSearch23502416.FirstNameInfo, new RecordItemIndex(9));
            repo.CustomerSearch23502416.FirstName.PressKeys(searchFirstName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CustomerSearch23502416.ButtonOK' at 19;10.", repo.CustomerSearch23502416.ButtonOKInfo, new RecordItemIndex(10));
            repo.CustomerSearch23502416.ButtonOK.Click("19;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VIPlayers23502416.ImBackSplash' at 1146;111.", repo.VIPlayers23502416.ImBackSplashInfo, new RecordItemIndex(11));
            repo.VIPlayers23502416.ImBackSplash.Click("1146;111");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VIPlayers23502416' at 29;49.", repo.VIPlayers23502416.SelfInfo, new RecordItemIndex(12));
            repo.VIPlayers23502416.Self.Click("29;49");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Player.Exit' at 121;13.", repo.Player.ExitInfo, new RecordItemIndex(13));
            repo.Player.Exit.Click("121;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Error.ButtonYes' at 45;13.", repo.Error.ButtonYesInfo, new RecordItemIndex(14));
            repo.Error.ButtonYes.Click("45;13");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
