///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestPlayer
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestPlayerRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("68a53fc2-19d3-4efa-ac01-c95a7cf8df96")]
    public partial class TestPlayerRepository : RepoGenBaseFolder
    {
        static TestPlayerRepository instance = new TestPlayerRepository();
        TestPlayerRepositoryFolders.PasswordAppFolder _password;
        TestPlayerRepositoryFolders.VIPlayers23502416AppFolder _viplayers23502416;
        TestPlayerRepositoryFolders.PlayerAppFolder _player;
        TestPlayerRepositoryFolders.CustomerSearch23502416AppFolder _customersearch23502416;
        TestPlayerRepositoryFolders.ErrorAppFolder _error;
        TestPlayerRepositoryFolders.Form1AppFolder _form1;
        TestPlayerRepositoryFolders.PlayerAccountManagement23502416AppFolder _playeraccountmanagement23502416;

        /// <summary>
        /// Gets the singleton class instance representing the TestPlayerRepository element repository.
        /// </summary>
        [RepositoryFolder("68a53fc2-19d3-4efa-ac01-c95a7cf8df96")]
        public static TestPlayerRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestPlayerRepository() 
            : base("TestPlayerRepository", "/", null, 0, false, "68a53fc2-19d3-4efa-ac01-c95a7cf8df96", ".\\RepositoryImages\\TestPlayerRepository68a53fc2.rximgres")
        {
            _password = new TestPlayerRepositoryFolders.PasswordAppFolder(this);
            _viplayers23502416 = new TestPlayerRepositoryFolders.VIPlayers23502416AppFolder(this);
            _player = new TestPlayerRepositoryFolders.PlayerAppFolder(this);
            _customersearch23502416 = new TestPlayerRepositoryFolders.CustomerSearch23502416AppFolder(this);
            _error = new TestPlayerRepositoryFolders.ErrorAppFolder(this);
            _form1 = new TestPlayerRepositoryFolders.Form1AppFolder(this);
            _playeraccountmanagement23502416 = new TestPlayerRepositoryFolders.PlayerAccountManagement23502416AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("68a53fc2-19d3-4efa-ac01-c95a7cf8df96")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Password folder.
        /// </summary>
        [RepositoryFolder("5c31dd4e-a786-493e-a458-375330af508c")]
        public virtual TestPlayerRepositoryFolders.PasswordAppFolder Password
        {
            get { return _password; }
        }

        /// <summary>
        /// The VIPlayers23502416 folder.
        /// </summary>
        [RepositoryFolder("40bc798b-7db0-42c7-ae9c-8fd1f608cdaa")]
        public virtual TestPlayerRepositoryFolders.VIPlayers23502416AppFolder VIPlayers23502416
        {
            get { return _viplayers23502416; }
        }

        /// <summary>
        /// The Player folder.
        /// </summary>
        [RepositoryFolder("8b678b3d-2bc0-4215-9587-2913d4ca7f81")]
        public virtual TestPlayerRepositoryFolders.PlayerAppFolder Player
        {
            get { return _player; }
        }

        /// <summary>
        /// The CustomerSearch23502416 folder.
        /// </summary>
        [RepositoryFolder("02ccb66c-1229-4ac0-9fd9-5a2ac8448a94")]
        public virtual TestPlayerRepositoryFolders.CustomerSearch23502416AppFolder CustomerSearch23502416
        {
            get { return _customersearch23502416; }
        }

        /// <summary>
        /// The Error folder.
        /// </summary>
        [RepositoryFolder("8c96a1bb-dafd-47dc-b614-6b2c376451a6")]
        public virtual TestPlayerRepositoryFolders.ErrorAppFolder Error
        {
            get { return _error; }
        }

        /// <summary>
        /// The Form1 folder.
        /// </summary>
        [RepositoryFolder("7ea73632-c2ab-4d2b-8549-e20233bd3567")]
        public virtual TestPlayerRepositoryFolders.Form1AppFolder Form1
        {
            get { return _form1; }
        }

        /// <summary>
        /// The PlayerAccountManagement23502416 folder.
        /// </summary>
        [RepositoryFolder("37e6347c-168f-44a7-bf73-83a32e577ef4")]
        public virtual TestPlayerRepositoryFolders.PlayerAccountManagement23502416AppFolder PlayerAccountManagement23502416
        {
            get { return _playeraccountmanagement23502416; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TestPlayerRepositoryFolders
    {
        /// <summary>
        /// The PasswordAppFolder folder.
        /// </summary>
        [RepositoryFolder("5c31dd4e-a786-493e-a458-375330af508c")]
        public partial class PasswordAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _passwordInfo;
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new Password  folder.
            /// </summary>
            public PasswordAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Password", "/form[@name='GetPassword']", parentFolder, 30000, null, true, "5c31dd4e-a786-493e-a458-375330af508c", "")
            {
                _passwordInfo = new RepoItemInfo(this, "Password", "?/?/text[@name='Password']", "?/?/text[@name='Password']", 30000, null, "fc41d12f-8e99-427a-97d1-66f6ad810bc7");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "?/?/button[@name='Btn_OK']", "?/?/button[@name='Btn_OK']", 30000, null, "8ce7d299-8e9b-444f-9203-98613cf43c0a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5c31dd4e-a786-493e-a458-375330af508c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5c31dd4e-a786-493e-a458-375330af508c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("fc41d12f-8e99-427a-97d1-66f6ad810bc7")]
            public virtual Ranorex.Text Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("fc41d12f-8e99-427a-97d1-66f6ad810bc7")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("8ce7d299-8e9b-444f-9203-98613cf43c0a")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("8ce7d299-8e9b-444f-9203-98613cf43c0a")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The VIPlayers23502416AppFolder folder.
        /// </summary>
        [RepositoryFolder("40bc798b-7db0-42c7-ae9c-8fd1f608cdaa")]
        public partial class VIPlayers23502416AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _imbacksplashInfo;

            /// <summary>
            /// Creates a new VIPlayers23502416  folder.
            /// </summary>
            public VIPlayers23502416AppFolder(RepoGenBaseFolder parentFolder) :
                    base("VIPlayers23502416", "/form[@name='Form1']", parentFolder, 30000, null, true, "40bc798b-7db0-42c7-ae9c-8fd1f608cdaa", "")
            {
                _imbacksplashInfo = new RepoItemInfo(this, "ImBackSplash", "picture[@name='ImBackSplash']", "picture[@name='ImBackSplash']", 30000, null, "de70dd93-0b43-42ad-96e2-0ba2485db32d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("40bc798b-7db0-42c7-ae9c-8fd1f608cdaa")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("40bc798b-7db0-42c7-ae9c-8fd1f608cdaa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ImBackSplash item.
            /// </summary>
            [RepositoryItem("de70dd93-0b43-42ad-96e2-0ba2485db32d")]
            public virtual Ranorex.Picture ImBackSplash
            {
                get
                {
                    return _imbacksplashInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The ImBackSplash item info.
            /// </summary>
            [RepositoryItemInfo("de70dd93-0b43-42ad-96e2-0ba2485db32d")]
            public virtual RepoItemInfo ImBackSplashInfo
            {
                get
                {
                    return _imbacksplashInfo;
                }
            }
        }

        /// <summary>
        /// The PlayerAppFolder folder.
        /// </summary>
        [RepositoryFolder("8b678b3d-2bc0-4215-9587-2913d4ca7f81")]
        public partial class PlayerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _managementInfo;
            RepoItemInfo _playerInfo;
            RepoItemInfo _exitInfo;

            /// <summary>
            /// Creates a new Player  folder.
            /// </summary>
            public PlayerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Player", "/contextmenu[@processname='Player']", parentFolder, 30000, null, false, "8b678b3d-2bc0-4215-9587-2913d4ca7f81", "")
            {
                _managementInfo = new RepoItemInfo(this, "Management", "?/?/menuitem[@accessiblename='Management']", "?/?/menuitem[@accessiblename='Management']", 30000, null, "bc1dc8e6-e65d-4b71-8d53-94176c621ce5");
                _playerInfo = new RepoItemInfo(this, "Player", "?/?/menuitem[@accessiblename='Player...']", "?/?/menuitem[@accessiblename='Player...']", 30000, null, "487cf429-3902-400d-a568-0b60edb905aa");
                _exitInfo = new RepoItemInfo(this, "Exit", "?/?/menuitem[@accessiblename='Exit']", "?/?/menuitem[@accessiblename='Exit']", 30000, null, "f3fc7afc-c433-40c8-9da0-ecb3cde75001");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8b678b3d-2bc0-4215-9587-2913d4ca7f81")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8b678b3d-2bc0-4215-9587-2913d4ca7f81")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Management item.
            /// </summary>
            [RepositoryItem("bc1dc8e6-e65d-4b71-8d53-94176c621ce5")]
            public virtual Ranorex.MenuItem Management
            {
                get
                {
                    return _managementInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Management item info.
            /// </summary>
            [RepositoryItemInfo("bc1dc8e6-e65d-4b71-8d53-94176c621ce5")]
            public virtual RepoItemInfo ManagementInfo
            {
                get
                {
                    return _managementInfo;
                }
            }

            /// <summary>
            /// The Player item.
            /// </summary>
            [RepositoryItem("487cf429-3902-400d-a568-0b60edb905aa")]
            public virtual Ranorex.MenuItem Player
            {
                get
                {
                    return _playerInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Player item info.
            /// </summary>
            [RepositoryItemInfo("487cf429-3902-400d-a568-0b60edb905aa")]
            public virtual RepoItemInfo PlayerInfo
            {
                get
                {
                    return _playerInfo;
                }
            }

            /// <summary>
            /// The Exit item.
            /// </summary>
            [RepositoryItem("f3fc7afc-c433-40c8-9da0-ecb3cde75001")]
            public virtual Ranorex.MenuItem Exit
            {
                get
                {
                    return _exitInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Exit item info.
            /// </summary>
            [RepositoryItemInfo("f3fc7afc-c433-40c8-9da0-ecb3cde75001")]
            public virtual RepoItemInfo ExitInfo
            {
                get
                {
                    return _exitInfo;
                }
            }
        }

        /// <summary>
        /// The CustomerSearch23502416AppFolder folder.
        /// </summary>
        [RepositoryFolder("02ccb66c-1229-4ac0-9fd9-5a2ac8448a94")]
        public partial class CustomerSearch23502416AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _nameInfo;

            /// <summary>
            /// Creates a new CustomerSearch23502416  folder.
            /// </summary>
            public CustomerSearch23502416AppFolder(RepoGenBaseFolder parentFolder) :
                    base("CustomerSearch23502416", "/form[@name='GetCustomerL']", parentFolder, 30000, null, true, "02ccb66c-1229-4ac0-9fd9-5a2ac8448a94", "")
            {
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "container[@name='Panel1']/?/?/text[@name='FirstName']", ".//text[@name='FirstName']", 30000, null, "f229f657-5a61-4dba-91c5-014903e63359");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "?/?/button[@name='Btn_OK']", "?/?/button[@name='Btn_OK']", 30000, null, "ab514659-1d1a-4eeb-ad7f-f5bd55087a9f");
                _nameInfo = new RepoItemInfo(this, "Name", "container[@name='Panel1']/?/?/text[@name='Name']", ".//text[@name='Name']", 30000, null, "c2f41255-d7c1-4c9c-b6f4-39cb22e49f59");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("02ccb66c-1229-4ac0-9fd9-5a2ac8448a94")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("02ccb66c-1229-4ac0-9fd9-5a2ac8448a94")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("f229f657-5a61-4dba-91c5-014903e63359")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("f229f657-5a61-4dba-91c5-014903e63359")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("ab514659-1d1a-4eeb-ad7f-f5bd55087a9f")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("ab514659-1d1a-4eeb-ad7f-f5bd55087a9f")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The Name item.
            /// </summary>
            [RepositoryItem("c2f41255-d7c1-4c9c-b6f4-39cb22e49f59")]
            public virtual Ranorex.Text Name
            {
                get
                {
                    return _nameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Name item info.
            /// </summary>
            [RepositoryItemInfo("c2f41255-d7c1-4c9c-b6f4-39cb22e49f59")]
            public virtual RepoItemInfo NameInfo
            {
                get
                {
                    return _nameInfo;
                }
            }
        }

        /// <summary>
        /// The ErrorAppFolder folder.
        /// </summary>
        [RepositoryFolder("8c96a1bb-dafd-47dc-b614-6b2c376451a6")]
        public partial class ErrorAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _buttonnoInfo;
            RepoItemInfo _buttonyesInfo;

            /// <summary>
            /// Creates a new Error  folder.
            /// </summary>
            public ErrorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Error", "/form[@name='none']", parentFolder, 30000, null, true, "8c96a1bb-dafd-47dc-b614-6b2c376451a6", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@name='OK']", "button[@name='OK']", 30000, null, "a120a343-f74d-4c08-9831-e55ae3ec00eb");
                _buttonnoInfo = new RepoItemInfo(this, "ButtonNo", "button[@name='No']", "button[@name='No']", 30000, null, "380e1e40-1634-4553-8f04-b7e5463dcfdd");
                _buttonyesInfo = new RepoItemInfo(this, "ButtonYes", "button[@name='Yes']", "button[@name='Yes']", 30000, null, "88162260-ee20-476c-ae75-f3960ec48223");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8c96a1bb-dafd-47dc-b614-6b2c376451a6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8c96a1bb-dafd-47dc-b614-6b2c376451a6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("a120a343-f74d-4c08-9831-e55ae3ec00eb")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("a120a343-f74d-4c08-9831-e55ae3ec00eb")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The ButtonNo item.
            /// </summary>
            [RepositoryItem("380e1e40-1634-4553-8f04-b7e5463dcfdd")]
            public virtual Ranorex.Button ButtonNo
            {
                get
                {
                    return _buttonnoInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonNo item info.
            /// </summary>
            [RepositoryItemInfo("380e1e40-1634-4553-8f04-b7e5463dcfdd")]
            public virtual RepoItemInfo ButtonNoInfo
            {
                get
                {
                    return _buttonnoInfo;
                }
            }

            /// <summary>
            /// The ButtonYes item.
            /// </summary>
            [RepositoryItem("88162260-ee20-476c-ae75-f3960ec48223")]
            public virtual Ranorex.Button ButtonYes
            {
                get
                {
                    return _buttonyesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonYes item info.
            /// </summary>
            [RepositoryItemInfo("88162260-ee20-476c-ae75-f3960ec48223")]
            public virtual RepoItemInfo ButtonYesInfo
            {
                get
                {
                    return _buttonyesInfo;
                }
            }
        }

        /// <summary>
        /// The Form1AppFolder folder.
        /// </summary>
        [RepositoryFolder("7ea73632-c2ab-4d2b-8549-e20233bd3567")]
        public partial class Form1AppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Form1  folder.
            /// </summary>
            public Form1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Form1", "/form[@controlname='Form1']", parentFolder, 30000, null, true, "7ea73632-c2ab-4d2b-8549-e20233bd3567", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7ea73632-c2ab-4d2b-8549-e20233bd3567")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7ea73632-c2ab-4d2b-8549-e20233bd3567")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The PlayerAccountManagement23502416AppFolder folder.
        /// </summary>
        [RepositoryFolder("37e6347c-168f-44a7-bf73-83a32e577ef4")]
        public partial class PlayerAccountManagement23502416AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttoncloseInfo;

            /// <summary>
            /// Creates a new PlayerAccountManagement23502416  folder.
            /// </summary>
            public PlayerAccountManagement23502416AppFolder(RepoGenBaseFolder parentFolder) :
                    base("PlayerAccountManagement23502416", "/form[@name='Player_AccountManagement']", parentFolder, 30000, null, true, "37e6347c-168f-44a7-bf73-83a32e577ef4", "")
            {
                _buttoncloseInfo = new RepoItemInfo(this, "ButtonClose", "?/?/button[@name='BtnClose']", "?/?/button[@name='BtnClose']", 30000, null, "622084e2-5940-49f8-9f6c-810a888c1ab5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("37e6347c-168f-44a7-bf73-83a32e577ef4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("37e6347c-168f-44a7-bf73-83a32e577ef4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonClose item.
            /// </summary>
            [RepositoryItem("622084e2-5940-49f8-9f6c-810a888c1ab5")]
            public virtual Ranorex.Button ButtonClose
            {
                get
                {
                    return _buttoncloseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonClose item info.
            /// </summary>
            [RepositoryItemInfo("622084e2-5940-49f8-9f6c-810a888c1ab5")]
            public virtual RepoItemInfo ButtonCloseInfo
            {
                get
                {
                    return _buttoncloseInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
